### ISSUE TITLE
Scene inspector

### ISSUE THREAD

**Issue by Kilbukas** [MeoMix/symbiants#36]
https://bevy-cheatbook.github.io/setup/bevy-tools.html

Need to investigate which option would work best.

**Comment by MeoMix** [comment]
I added bevy_egui_inspector under a conditional flag, dev-inspector.

It adds a lot of lag because of how many entities there are, but it seems to work fine and is relatively informative.

I'm not sure if this is useful for what you were trying to achieve, though. I found it mildly useful for confirming I didn't leave lingering resources after resetting sandbox.
